export const data =
[
 {
  "Date création": "2022-12-01",
  "Heure création": "08:33:57",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:01",
  "Client": "Menzeh Télécom ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Wise-Tech",
  "Modéle": "A1",
  "Couleur": "Blanc",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2120,
  "Prix unitaire": 2250,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 2250,
  "Bénéfice": 130
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:33:57",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:01",
  "Client": "Menzeh Télécom ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Wise-Tech",
  "Modéle": "A1",
  "Couleur": "Noir",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2120,
  "Prix unitaire": 2250,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 2250,
  "Bénéfice": 130
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:37:01",
  "Date cloture": "2022-12-08",
  "Heure cloture": "11:56:40",
  "Client": "Tani phone ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Accessoire",
  "Marque": "Hoco",
  "Modéle": "Bluetooth ES41",
  "Couleur": "Aucune",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 3843,
  "Prix unitaire": 3940,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 3940,
  "Bénéfice": 97
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:43:03",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:18",
  "Client": "Tani phone ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Maxfone",
  "Modéle": 308,
  "Couleur": "Noir Rouge",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2450,
  "Prix unitaire": 2700,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 2700,
  "Bénéfice": 250
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:43:03",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:18",
  "Client": "Tani phone ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Maxfone",
  "Modéle": "M118",
  "Couleur": "Noir",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2750,
  "Prix unitaire": 3000,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 3000,
  "Bénéfice": 250
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:43:03",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:18",
  "Client": "Tani phone ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Tablet-I5",
  "Modéle": "C02",
  "Couleur": "Noir Rouge",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2200,
  "Prix unitaire": 2450,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 2450,
  "Bénéfice": 250
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:45:55",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:39",
  "Client": "Tani phone ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Starlight",
  "Modéle": "M04",
  "Couleur": "Noir",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2100,
  "Prix unitaire": 2400,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 2400,
  "Bénéfice": 300
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "08:45:55",
  "Date cloture": "2022-12-01",
  "Heure cloture": "14:22:39",
  "Client": "Tani phone ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Starlight",
  "Modéle": "M09",
  "Couleur": "Noir Rouge",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2500,
  "Prix unitaire": 2800,
  "Réduction": 0,
  "Quantité": 1,
  "Gratuits": 0,
  "Prix Total": 2800,
  "Bénéfice": 300
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "09:18:43",
  "Date cloture": "2022-12-04",
  "Heure cloture": "10:56:39",
  "Client": "Osmane Télécom ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Maxfone",
  "Modéle": "M128",
  "Couleur": "Bleu",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2750,
  "Prix unitaire": 3000,
  "Réduction": 0,
  "Quantité": 2,
  "Gratuits": 0,
  "Prix Total": 6000,
  "Bénéfice": 500
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "09:18:43",
  "Date cloture": "2022-12-04",
  "Heure cloture": "10:56:39",
  "Client": "Osmane Télécom ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Maxfone",
  "Modéle": "M128",
  "Couleur": "Gold",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2750,
  "Prix unitaire": 3000,
  "Réduction": 0,
  "Quantité": 2,
  "Gratuits": 0,
  "Prix Total": 6000,
  "Bénéfice": 500
 },
 {
  "Date création": "2022-12-01",
  "Heure création": "09:18:43",
  "Date cloture": "2022-12-04",
  "Heure cloture": "10:56:39",
  "Client": "Osmane Télécom ",
  "Catégorie client": "Semi gros",
  "Wilaya": "Oran",
  "Magasin": 11,
  "Vendeur": "Azouz",
  "Famille": "Simple Phone",
  "Marque": "Maxfone",
  "Modéle": "M128",
  "Couleur": "Noir",
  "Catalogue1": "Aucun",
  "Catalogue2": "Acune",
  "Catalogue3": "Acune",
  "Cout": 2750,
  "Prix unitaire": 3000,
  "Réduction": 0,
  "Quantité": 2,
  "Gratuits": 0,
  "Prix Total": 6000,
  "Bénéfice": 500
 }
]